@RealState.Api_HostAddress = http://localhost:5001
POST {{RealState.Api_HostAddress}}/auth/register
Content-Type: application/json

{
    "firstName": "Saitama",
    "lastName": "Sep",
    "email": "saitama@gmail.com",
    "password": "mypassword000"
}

###
