@RealState.Api_HostAddress=https://localhost:5001
@token=yJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI0Yjc5NzU2Yi01ODEyLTRkMTQtYmJiYi1iOGUzOThmN2MyOGMiLCJnaXZlbl9uYW1lIjoiU2FpdGFtYSIsImZhbWlseV9uYW1lIjoiU2VwIiwianRpIjoiN2Y1NTU3MTUtNGJmOC00ZWU0LTlkMTUtZjRiNzdmMzczOTYxIiwiZXhwIjoxNzM3NDExMDI3LCJpc3MiOiJSZWFsU3RhdGUiLCJhdWQiOiJSZWFsU3RhdGUifQ.D2cUd8t95sIB731lGsfFQ4RntvaowjW53mEEx6JJUDI
POST {{RealState.Api_HostAddress}}/properties/
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "Name": "Luxury Downtown Apartment",
    "Address": {
        "Street": "123 Main Street",
        "City": "New York",
        "ZipCode": "10001"
    },
    "Price": {
        "Amount": 555523,
        "Currency": "USD"
    },
    "CodeInternal": "PDRES123",
    "Year": 2020,
    "OwnerId": "87c18371-ce95-40a8-b32e-39c3d8b16c94"
}

###
