@RealState.Api_HostAddress=https://localhost:7088
@token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIwZTNjYjE2ZC0wY2QxLTRkMTQtYTA1Yi05YWE0YmZkZDJiNTkiLCJnaXZlbl9uYW1lIjoiU2FpdGFtYSIsImZhbWlseV9uYW1lIjoiU2VwIiwianRpIjoiNjcxNmM1OGItNzlmYi00YWE0LWJmODItNGJiNzFjODcyMTA5IiwiZXhwIjoxNzM3MzE2NzE0LCJpc3MiOiJSZWFsU3RhdGUiLCJhdWQiOiJSZWFsU3RhdGUifQ.bYKEnKLhnzcyJc0QIT3D4IvoGnOgbUhhhu_J6IhH1FM

POST {{RealState.Api_HostAddress}}/properties/filter
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "Name": ,
    "MinPrice": 0,
    "MaxPrice": 100000000000,
    "City": ,
    "Year": ,
    "Page": 1,
    "PageSize": 10
}

###
