@RealState.Api_HostAddress=https://localhost:7088
@token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxNTkzOGJlZC1iMDI5LTRkNWEtYWM3Mi1hNDc3NDgyNWU2NzgiLCJnaXZlbl9uYW1lIjoiU2FpdGFtYSIsImZhbWlseV9uYW1lIjoiU2VwIiwianRpIjoiMDkyODQ4M2QtYjE4MS00M2IyLWE5NjEtZDM0MThlODZmYzI0IiwiZXhwIjoxNzM3Mzg3NTA0LCJpc3MiOiJSZWFsU3RhdGUiLCJhdWQiOiJSZWFsU3RhdGUifQ.BPJGkbcYaLz-YgkPik2TjJIBce6A0fuFWFK1cuVK17w

POST {{RealState.Api_HostAddress}}/properties/filter
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "Name":"Luxury Downtown Apartment",
    "MinPrice": 0,
    "MaxPrice": 100000000,
    "City": "New York",
    "Year": 2020,
    "Page": 1,
    "PageSize": 10
}

###
