@RealState.Api_HostAddress=https://localhost:5001
@token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIwZTNjYjE2ZC0wY2QxLTRkMTQtYTA1Yi05YWE0YmZkZDJiNTkiLCJnaXZlbl9uYW1lIjoiU2FpdGFtYSIsImZhbWlseV9uYW1lIjoiU2VwIiwianRpIjoiZjRjYmJlZTAtNTMwMy00M2E1LTg4OTUtNGVkZGRjOGRkM2FkIiwiZXhwIjoxNzM3MzE3MTg2LCJpc3MiOiJSZWFsU3RhdGUiLCJhdWQiOiJSZWFsU3RhdGUifQ.PsSXXSZ5rY2XElVigPxFpA8eHA4gQdReA0ONleIx2iU
@id=54f3795e-b6cc-4477-9579-ad5ec4c2e0fa

PATCH  {{RealState.Api_HostAddress}}/properties/{{id}}/price
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "Id": "54f3795e-b6cc-4477-9579-ad5ec4c2e0fa",
    "Price": {
        "Amount": 555523,
        "Currency": "USD"
    }
}

###
