@RealState.Api_HostAddress=https://localhost:5001
@token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI4OTMyZTZkMS03YTE4LTRkZjgtYTk1MC0xZWExNzJhM2ZiNzIiLCJnaXZlbl9uYW1lIjoiU2FpdGFtYSIsImZhbWlseV9uYW1lIjoiU2VwIiwianRpIjoiZmI3NmNkZTUtOGQyMy00MzRjLThiNWUtOGM3MzdlMDIzMjUzIiwiZXhwIjoxNzM3MzIzNDM3LCJpc3MiOiJSZWFsU3RhdGUiLCJhdWQiOiJSZWFsU3RhdGUifQ.mvKJQhFcZrCqiNmNwJV2s3UxYsSIjkwJ7geDQGLuyH4
POST {{RealState.Api_HostAddress}}/properties/owners
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "name": "John Doe",
  "address": {
    "street": "123 Main St",
    "city": "Anytown",
    "zipcode": "USA"
  },
  "birthday": "1980-01-15" 
}

